pub const NPROC: usize = 64;
pub const NCPU: usize = 8;
pub const NOFILE: usize = 16;
pub const NFILE: usize = 100;
pub const NINODE: usize = 50;
pub const NDEV: usize = 10;
pub const ROOTDEV: usize = 1;   // device number of file system root disk
pub const MAXARG: usize = 32;
pub const MAXOPBLOCKS: usize = 10; // max data blocks in on-disk log
pub const LOGSIZE: usize = MAXOPBLOCKS * 3;
pub const NBUF: usize = MAXOPBLOCKS * 3;
pub const FSSIZE: usize = 1000; // size of file system in blocks
pub const MAXPATH: usize = 128; // maximum file path name
